name: EPUB Accessibility Techniques
description: Issue related to the EPUB Accessibility Techniques Working Group Note
labels: Spec-A11yTechniques
body: 
  - type: markdown
    attributes:
     value: "## Issue on the EPUB Accessibility Techniques WG Note"
  - type: markdown
    attributes:
     value: __Before opening an issue__, please check that it has not already been resolved in the [latest version](https://www.w3.org/TR/epub-a11y-tech-111/)
  - type: input
    id: section
    attributes:
      label: Section
      description: Please provide a link to the relevant section of the specification
    validations:
      required: false 
  - type: textarea
    id: problem
    attributes:
      label: Describe the problem
      description: What is not working? What would you like to see improved? For bug reports, cite the relevant text from the specification.
    validations:
      required: true
  - type: textarea
    id: fix
    attributes:
      label: Describe the fix or new feature you propose
    validations:
      required: false
