name: General issue template
description: Issue on the EPUB 3 specifications or related Working Group Notes
body: 
  - type: markdown
    attributes:
     value: "## Before opening an issue"
  - type: markdown
    attributes:
     value: |
       This repository is only for issues with the following W3C documents; please, use the appropriate issue templates for questions/issues related to those documents. Questions or issues with specific reading systems, achieving specific styling, understanding validation errors, and similar will be considered as out of scope and will be closed without further action.
       * [EPUB 3](https://www.w3.org/TR/epub-34/), Recommendation
       * [EPUB Reading Systems](https://www.w3.org/TR/epub-rs-34/), Recommendation
       * [EPUB Accessibility](https://www.w3.org/TR/epub-a11y-111/), Recommendation
       * [EPUB Accessibility Techniques](https://www.w3.org/TR/epub-a11y-tech-111/), WG Note
       * [EPUB 3 Overview](https://www.w3.org/TR/epub-overview-34/), WG Note
       * [EPUB Fixed Layout Accessibility](https://www.w3.org/TR/epub-fxl-a11y/), WG Note
       * [EPUB Accessibility - EU Accessibility Act Mapping](https://www.w3.org/TR/epub-a11y-eaa-mapping/), WG Note
       * [The EPUB Accessibility exemption property](https://www.w3.org/TR/epub-a11y-exemption/), WG Note
       * [EPUB 3 Structural Semantics Vocabulary](https://www.w3.org/TR/epub-ssv/), WG Note
       * [EPUB 3 Multiple-Rendition Publications](https://www.w3.org/TR/epub-multi-rend/), WG Note
       * [EPUB 3 Text-to-Speech Enhancements](https://www.w3.org/TR/epub-tts/), WG Note
       * [EPUB Type to ARIA Role Authoring Guide](https://www.w3.org/TR/epub-aria-authoring/), WG Note
       
       Some possible alternative locations get help to your problems:
       
       * the [epub forum](https://www.mobileread.com/forums/forumdisplay.php?f=179) at mobileread
       * the [W3C publishing community group](https://github.com/w3c/publishingcg/issues)
       * the [ebooks section](https://ebooks.stackexchange.com/questions/tagged/epub) at stackexchange
  - type: textarea
    id: problem
    attributes:
      label: Describe the problem
      description: What is not working? What would you like to see improved? For bug reports, cite the relevant text from the specification.
    validations:
      required: true
  - type: textarea
    id: fix
    attributes:
      label: Describe the fix or new feature you propose
    validations:
      required: false
